server:
  port: 8301
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  #  环境设置 dev、test、prod
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev
  application:
    name: service-vod
  datasource:
    #    数据库配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///glkt-vod
    username:
    password:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

# mybatis 日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/zhr/mapper/xml/*.xml
# 腾讯云配置信息
tencent:
  cos:
    file:
      region:
      secretid:
      secretkey:
      bucketname: