# 服务端口
server:
  port: 8333
spring:
  application:
    name: service-gateway  # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  # nacos服务地址
    gateway:
      discovery:
        locator:
          enabled: true  #使用服务发现路由
        actuator:
          enabled: true
      routes:
        - id: service-vod   #service-vod模块配置
          uri: lb://service-vod   #设置路由的uri
          predicates:
            - Path=/*/vod/**   #设置路由断言,代理servicerId为auth-service的/auth/路径
        - id: service-order
          uri: lb://service-order
          predicates:
            - Path=/*/order/**
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/*/user/**
        - id: service-activity
          uri: lb://service-activity
          predicates:
            - Path=/*/activity/**
management:
  endpoints:
    web:
      exposure:
        include: "*"
